#!/usr/bin/env bash

set -e
set -u

GIT_DIR=$(git rev-parse --git-dir)
export GIT_DIR

plugins=()
plugins=$(git config --get-all hooks.enabled-plugins)

if [[ ${#plugins[@]} -gt 0 ]]; then
	echo -e "\033[1mrunnig pre-commit plugins:\033[0m"
fi

test -f "$GIT_DIR"/CHERRY_PICK_HEAD && exit 0

for enabled_plugin in ${plugins[@]}
do
	if [ -f "$GIT_DIR/hooks/$enabled_plugin/pre-commit" ]; then
		echo -e "\033[34m$enabled_plugin\033[0m"
		if ! "$GIT_DIR/hooks/$enabled_plugin/pre-commit"
		then
			exit 1
		fi
	fi
done

